project:
  type: website
  output-dir: docs

website:
  # announcement:
  #   icon: info-circle
  #   dismissable: false
  #   type: primary
  #   position: above-navbar
  #   content: "This website is currently under development!"
  title: "MEDS Career & Professional Develoment"
  favicon: images/bren-meds-hex.png
  navbar:
    title: "MEDS"
    right:
      - href: index.qmd
        text: home
      - text: summer
        menu:
          - text: week 5 (09/02) - **intro**
            href: materials/intro.qmd
          # - text: week 6 (09/10) - **values**
          #   href: materials/values.qmd
      - text: fall
        menu:
          - text: orientation (date tbd) - **resume** 
            href: materials/resume.qmd
          - text: orientation (date tbd) - **personal website** 
            href: materials/personal-website.qmd
          - text: week 1 (09/30) - **AI for EDS 1**
            href: materials/GenAI1.qmd
          - text: week 2 (10/07) - **networking**
            href: materials/networking.qmd
          - text: week 3 (10/14) - **customizing websites**
            href: materials/customizing-websites.qmd
          - text: week 4 (10/21) - **relationship team**
            href: materials/relationship-team.qmd
          - text: week 5 (10/28) - **career panel**
            href: materials/fall-panel.qmd
          - text: week 5 (10/29) - **CV (optional)**
            href: materials/cv.qmd
          - text: week 6 (11/04) - **integrating a blog**
            href: materials/blog.qmd
          - text: week 7 (11/09) - **AI for EDS 2**
            href: materials/GenAI2.qmd
      # - text: winter
      #   menu:
      #     - text: week 1 (01/07) - **job search kickoff**
      #       href: materials/job-search.qmd
      #     - text: week 2 (01/14) - **professional development skills**
      #       href: materials/professional-dev.qmd
      #     - text: week 4 (01/28) - **career panel**
      #       href: materials/winter-panel.qmd
      #     - text: week 5 (02/04) - **resume & cover letter**
      #       href: materials/resume-cover-letter.qmd
      #     - text: week 6 (02/11) - **LinkedIn**
      #       href: materials/linkedin.qmd
      - text: BrenConnect
        href: http://brenconnect.bren.ucsb.edu
        target: _blank
      - icon: github
        href: https://github.com/UCSB-MEDS/career-professional-dev
        target: _blank

  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/UCSB-MEDS/career-professional-dev){target="_blank"} and [Quarto](https://quarto.org/){target="_blank"}
    #left: This work is licensed under \<your preferred license\> 

format:
  html:
    theme: meds-website-styles.scss
    page-layout: full
    toc: true
    title-block-banner: true



