---
title: "Personal Branding for Environmental Data Scientists"
subtitle: "Orienatation | Day 3"
description: "Wednesday, September 24^th^, 2025"
---

::: {.center-text .body-text-l}
**ADD IMAGE HERE**
:::

<br>

## {{< fa box-open title="an open box" >}} Anticipated deliverable(s) {#anticipated-deliverables}

By the end of today's workshop, you should have:

- your personal branding guide

## {{< fa book-open title="an open book" >}} Learning objectives {#learning-objectives}

TBD 

## {{< fa clipboard-list title="a clipboard with a To Do list" >}} Pre-class Prep {#pre-class-prep}

Please be sure to complete the following before class:

### A. tbd
### B. tbd

## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Workshop Materials {#workshop-materials}

| Content Type | Materials              | Notes |
|--------------|------------------------|-------|
| TBD          | TBD                    | TBD   |
: {.hover .bordered tbl-colwidths="[20,30,50]"} 

## {{< fa plus title="plus" >}} What should I continue working on? {#continue-working}

- [**Seek feedback on your personal brand from those who know you well.**]{.teal-text} Would they use the same adjectives to describe you? What strengths and characteristics do they perceive that you hadn’t identified yourself? What emotions do your colors, fonts, imagery, and tone evoke? It’s important to remember that your personal brand can (and should) evolve with you! 